# Generated by Django 5.1.6 on 2026-04-10 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "₱5 Plan"', max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Price in Philippine Peso (integer)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('speed_limit', models.DecimalField(blank=True, decimal_places=1, help_text='Optional speed cap in Mbps', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WiFi Plan',
                'verbose_name_plural': 'WiFi Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, unique=True)),
                ('device_name', models.CharField(help_text='e.g., "Admin laptop"', max_length=100)),
                ('added_by', models.CharField(default='admin', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Whitelisted Device',
                'verbose_name_plural': 'Whitelisted Devices',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes_purchased', models.PositiveIntegerField()),
                ('remaining_minutes', models.FloatField(default=0)),
                ('amount_paid', models.PositiveIntegerField(help_text='Total amount paid in ₱')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paused', 'Paused')], default='active', max_length=10)),
                ('voucher_code', models.CharField(blank=True, help_text='6-character voucher for session extension', max_length=10, null=True, unique=True)),
                ('bandwidth_used_mb', models.FloatField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sessions_app.plan')),
            ],
            options={
                'verbose_name': 'WiFi Session',
                'verbose_name_plural': 'WiFi Sessions',
                'ordering': ['-time_in'],
            },
        ),
        migrations.CreateModel(
            name='CoinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Total amount from this insertion')),
                ('denomination', models.PositiveIntegerField(choices=[(1, '₱1'), (5, '₱5'), (10, '₱10'), (20, '₱20')], help_text='Coin denomination')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_events', to='sessions_app.session')),
            ],
            options={
                'verbose_name': 'Coin Event',
                'verbose_name_plural': 'Coin Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
