# Generated by Django 5.1.6 on 2026-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinevent',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Device MAC associated with this payment, when known', max_length=17, null=True),
        ),
    ]
