# Generated by Django 5.1.6 on 2026-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_coinevent_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
