# Generated by Django 4.2.16 on 2026-04-15 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_session_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, unique=True)),
                ('last_ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(default='suspicious_activity', max_length=64)),
                ('evidence', models.TextField(blank=True, default='')),
                ('detection_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('blocked', 'Blocked'), ('false_positive', 'False Positive'), ('cleared', 'Cleared')], default='new', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Suspicious Device',
                'verbose_name_plural': 'Suspicious Devices',
                'ordering': ['-last_detected_at'],
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='user_agent',
        ),
    ]
