# Generated by Django 4.2.16 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0004_suspiciousdevice_remove_session_user_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinInsertRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mac_address", models.CharField(help_text="Format: AA:BB:CC:DD:EE:FF", max_length=17)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("purpose", models.CharField(choices=[("start", "Start Session")], default="start", max_length=10)),
                ("expected_amount", models.PositiveIntegerField(default=0, help_text="Amount needed to complete this request")),
                ("credited_amount", models.PositiveIntegerField(default=0, help_text="Current unconsumed credited amount")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="coin_insert_requests",
                        to="sessions_app.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin Insert Request",
                "verbose_name_plural": "Coin Insert Requests",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
