# Generated by Django 5.1.6 on 2026-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0006_session_pause_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='speed_limit_upload',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Upload speed cap in Mbps (defaults to download speed if blank)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='speed_limit',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Download speed cap in Mbps', max_digits=5, null=True),
        ),
    ]
