# Generated by Django 5.1.6 on 2026-08-15 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0007_add_upload_speed_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Amount paid in this transaction')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions_app.plan')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='sessions_app.session')),
            ],
            options={
                'verbose_name': 'Purchase Transaction',
                'verbose_name_plural': 'Purchase Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
