# Generated by Django 5.1.6 on 2026-08-15 16:46

from django.db import migrations

def backfill_purchases(apps, schema_editor):
    Session = apps.get_model('sessions_app', 'Session')
    PurchaseTransaction = apps.get_model('sessions_app', 'PurchaseTransaction')
    
    # Create one PurchaseTransaction for each Session covering its full amount_paid
    purchases = []
    for session in Session.objects.filter(amount_paid__gt=0):
        purchases.append(
            PurchaseTransaction(
                session=session,
                plan=session.plan,
                amount=session.amount_paid,
                timestamp=session.time_in
            )
        )
    PurchaseTransaction.objects.bulk_create(purchases)


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0008_purchasetransaction'),
    ]

    operations = [
        migrations.RunPython(backfill_purchases, migrations.RunPython.noop),
    ]
