# Generated by Django 5.1.6 on 2026-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0009_backfill_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pause_duration_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum total hours a session can remain paused (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='pause_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of times this plan can be paused (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='session',
            name='pause_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times paused'),
        ),
    ]
