# Generated by Django 5.1.6 on 2026-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0010_plan_pause_duration_limit_plan_pause_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Device MAC Address', max_length=17, unique=True)),
                ('points', models.PositiveIntegerField(default=0, help_text='Accumulated Gamification Points')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current Daily Connection Streak')),
                ('last_connected_date', models.DateField(blank=True, help_text='Date of last connection', null=True)),
                ('spins_today', models.PositiveIntegerField(default=0, help_text='Number of wheel spins today')),
                ('last_spin_date', models.DateField(blank=True, help_text='Date of last wheel spin', null=True)),
            ],
            options={
                'verbose_name': 'Device Profile',
                'verbose_name_plural': 'Device Profiles',
            },
        ),
        migrations.CreateModel(
            name='SpinPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Prize Name (e.g. '30 Mins', 'Try Again')", max_length=50)),
                ('minutes_reward', models.PositiveIntegerField(default=0, help_text='Minutes added to session (0 for Try Again)')),
                ('probability_weight', models.PositiveIntegerField(default=10, help_text='Higher weight = higher chance to win')),
                ('is_active', models.BooleanField(default=True, help_text='Is this prize currently active on the wheel?')),
            ],
            options={
                'verbose_name': 'Spin Prize',
                'verbose_name_plural': 'Spin Prizes',
            },
        ),
    ]
