# Generated by Django 5.1.6 on 2026-08-18 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0011_deviceprofile_spinprize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(help_text='Unique code to join the group', max_length=10, unique=True)),
                ('max_devices', models.PositiveIntegerField(help_text='Maximum allowed devices')),
                ('total_price', models.PositiveIntegerField(help_text='Total amount paid in ₱')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Session Group',
                'verbose_name_plural': 'Session Groups',
                'ordering': ['-time_in'],
            },
        ),
        migrations.AddField(
            model_name='coininsertrequest',
            name='group_pass_devices',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coininsertrequest',
            name='group_pass_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coininsertrequest',
            name='is_group_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sessions_app.plan'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='sessions_app.sessiongroup'),
        ),
    ]
