# Generated by Django 5.1.6 on 2026-08-24 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0013_sessiongroup_independent_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinprize',
            name='pause_duration_limit',
            field=models.PositiveIntegerField(default=0, help_text='Max hours a free session can remain paused (0 = unli)'),
        ),
        migrations.AddField(
            model_name='spinprize',
            name='pause_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum pauses for free sessions (0 = unli)'),
        ),
        migrations.AddField(
            model_name='spinprize',
            name='speed_limit',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Download speed cap in Mbps (defaults to global if blank)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='spinprize',
            name='speed_limit_upload',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Upload speed cap in Mbps (defaults to download if blank)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sessiongroup',
            name='max_devices',
            field=models.PositiveIntegerField(help_text='Maximum allowed redemptions'),
        ),
        migrations.AlterField(
            model_name='sessiongroup',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the group pass was purchased'),
        ),
    ]
