# Generated by Django 5.1.6 on 2026-08-31 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0014_spinprize_pause_duration_limit_spinprize_pause_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiongroup',
            name='redeemed_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this code has been redeemed (any session status).'),
        ),
        migrations.AlterField(
            model_name='session',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='sessions_app.plan'),
        ),
    ]
