# Generated by Django 5.1.6 on 2026-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0016_session_initial_bandwidth_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pause_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Total pauses allowed for this session (None = inherit from plan, 0 = unlimited)', null=True),
        ),
    ]
