# Generated by Django 5.1.6 on 2026-09-20 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0017_session_pause_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinevent',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, help_text='Device MAC associated with this payment, when known', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='coinevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coininsertrequest',
            name='mac_address',
            field=models.CharField(db_index=True, help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17),
        ),
        migrations.AlterField(
            model_name='coininsertrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='mac_address',
            field=models.CharField(db_index=True, help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paused', 'Paused')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_in',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
