upstream iconnect_app {
    server unix:/run/gunicorn/pisowifi.sock fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;

    # Set to Orange Pi hostname/IP as needed.
    server_name _;

    client_max_body_size 20m;

    location /static/ {
        alias /opt/iconnect/pisowifi/staticfiles/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location /media/ {
        alias /opt/iconnect/pisowifi/media/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        include proxy_params;
        proxy_pass http://iconnect_app;
        proxy_redirect off;
        proxy_read_timeout 120s;
    }
}
