# Generated by Django 5.1.6 on 2026-04-10 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Announcement message for students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRevenueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('avg_session_minutes', models.FloatField(default=0)),
                ('peak_hour', models.PositiveIntegerField(blank=True, help_text='Hour with most sessions (0-23)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Revenue Summary',
                'verbose_name_plural': 'Daily Revenue Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g., "ALLAN H3 Board"', max_length=255)),
                ('amount', models.PositiveIntegerField(help_text='Cost in ₱')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Project Cost',
                'verbose_name_plural': 'Project Costs',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='RevenueGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('target_amount', models.PositiveIntegerField(help_text='Target revenue in ₱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Revenue Goal',
                'verbose_name_plural': 'Revenue Goals',
                'ordering': ['-created_at'],
            },
        ),
    ]
