# Generated by Django 5.1.6 on 2026-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_operatingexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_anti_tethering', models.BooleanField(default=False, help_text='Block hotspot sharing by fixing TTL to 1')),
                ('enable_sqm', models.BooleanField(default=False, help_text='Enable CAKE Smart Queue Management for anti-bufferbloat')),
                ('isp_download_speed', models.PositiveIntegerField(default=100, help_text='Total ISP Download Speed (Mbps)')),
                ('isp_upload_speed', models.PositiveIntegerField(default=100, help_text='Total ISP Upload Speed (Mbps)')),
                ('enable_dark_mode', models.BooleanField(default=False, help_text='Force dark mode for the admin dashboard')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=20, help_text='Maximum allowed simultaneous connected users')),
                ('global_pause_limit_hours', models.PositiveIntegerField(default=24, help_text='Global fallback max pause duration in hours (0 = unlimited)')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
