# Generated by Django 5.1.6 on 2026-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_pause_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Seconds device must be unreachable before auto-pausing (Default: 300)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_auto_pause_resume',
            field=models.BooleanField(default=False, help_text='Automatically pause sessions when disconnected, and resume when reconnected'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_internet_check',
            field=models.BooleanField(default=False, help_text='Auto-disable coin insertion when the ISP/Internet is down'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='insert_coin_countdown_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Seconds before the coin slot auto-cancels if no coins are inserted (Default: 120)'),
        ),
    ]
