# Generated by Django 5.1.6 on 2026-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_systemsettings_auto_pause_timeout_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='daily_spin_limit',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed spins per day per device'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_spin_wheel',
            field=models.BooleanField(default=False, help_text='Enable Spin the Wheel game for users'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='points_per_streak_day',
            field=models.PositiveIntegerField(default=5, help_text='Points awarded for connecting on consecutive days'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='spin_cost_points',
            field=models.PositiveIntegerField(default=10, help_text='Points required to spin the wheel'),
        ),
    ]
