# Generated by Django 5.1.6 on 2026-08-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_systemsettings_daily_spin_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='points_per_peso',
            field=models.PositiveIntegerField(default=1, help_text='Points awarded for every ₱1 spent'),
        ),
    ]
