# Generated by Django 5.1.6 on 2026-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_systemsettings_points_per_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_family_pass',
            field=models.BooleanField(default=False, help_text='Enable the Family/Group Pass feature'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='family_pass_base_rate',
            field=models.PositiveIntegerField(default=10, help_text='Base rate for 1 device per hour (₱)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='family_pass_device_rate',
            field=models.PositiveIntegerField(default=5, help_text='Rate per additional device per hour (₱)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='family_pass_max_devices',
            field=models.PositiveIntegerField(default=6, help_text='Maximum devices allowed in a single Family Pass group'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='family_pass_speed_limit',
            field=models.FloatField(default=5.0, help_text='Download speed limit per device in a Family Pass (Mbps)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='family_pass_speed_limit_upload',
            field=models.FloatField(default=5.0, help_text='Upload speed limit per device in a Family Pass (Mbps)'),
        ),
    ]
