# Generated by Django 5.1.6 on 2026-08-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_systemsettings_group_code_expiry_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, help_text='Device MAC address', max_length=17, null=True)),
                ('contact_info', models.CharField(blank=True, help_text='Optional Contact (Phone, Name, or Messenger)', max_length=100)),
                ('category', models.CharField(choices=[('coin_stuck', 'Coin Stuck / Not Credited'), ('no_internet', 'No Internet / Slow Speed'), ('timer_issue', 'Timer / Session Issue'), ('group_pass', 'Group Pass Problem'), ('other', 'Other Issue / Feedback')], default='other', max_length=30)),
                ('message', models.TextField(help_text='Issue description from customer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Operator resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Issue Report',
                'verbose_name_plural': 'Issue Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
