# Generated by Django 5.1.6 on 2026-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_issuereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_telegram_bot',
            field=models.BooleanField(default=True, help_text='Enable Telegram bot for remote management and alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, default='6261306648', help_text='Authorized Telegram Admin Chat ID', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='8946483111:AAEQBhy1vOqLFPdKIXjInvGjNrofI3TqgZg', help_text='Telegram Bot Token from @BotFather', max_length=150),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_notify_daily_summary',
            field=models.BooleanField(default=True, help_text='Send daily midnight sales summary'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_notify_isp_down',
            field=models.BooleanField(default=True, help_text='Send alert when ISP internet drops'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegram_notify_tickets',
            field=models.BooleanField(default=True, help_text='Send alerts when customer reports an issue ticket'),
        ),
    ]
