# Generated by Django 5.1.6 on 2026-09-03 15:02

from django.db import migrations, models


def enable_internet_check_existing(apps, schema_editor):
    SystemSettings = apps.get_model('dashboard', 'SystemSettings')
    SystemSettings.objects.all().update(enable_internet_check=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_systemsettings_enable_telegram_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_internet_check',
            field=models.BooleanField(default=True, help_text='Auto-disable coin insertion and auto-pause sessions when the ISP/Internet is down'),
        ),
        migrations.RunPython(enable_internet_check_existing, migrations.RunPython.noop),
    ]
