# Generated by Django 5.1.6 on 2026-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_systemsettings_enable_internet_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='coin_timer_extension_seconds',
            field=models.PositiveIntegerField(default=8, help_text='Seconds added to the remaining countdown each time a coin is inserted (Default: 8)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='coin_timer_max_seconds',
            field=models.PositiveIntegerField(default=180, help_text='Maximum total seconds the countdown can reach to prevent slot hogging (Safety ceiling, Default: 180)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='coin_timer_min_remaining_seconds',
            field=models.PositiveIntegerField(default=15, help_text='Minimum guaranteed seconds remaining on the timer after each coin is inserted (Default: 15)'),
        ),
    ]
