# Generated by Django 5.1.6 on 2026-09-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_systemsettings_coin_timer_extension_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_outage_announcement',
            field=models.BooleanField(default=True, help_text='Show real-time alert popup modal and play sound on captive portal when ISP is down'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_outage_auto_pause',
            field=models.BooleanField(default=True, help_text='Automatically freeze and pause active student sessions when ISP is down to protect customer time'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_internet_check',
            field=models.BooleanField(default=True, help_text='Master switch: monitor ISP connection and detect outages'),
        ),
    ]
