# Generated by Django 5.1.6 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_systemsettings_enable_outage_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_session_pause_cap',
            field=models.PositiveIntegerField(default=5, help_text='Maximum total pause chances a single session can hold at any time (0 = no cap)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_extend_amount_for_pause',
            field=models.PositiveIntegerField(default=5, help_text='Minimum extension payment (in Pesos) required to earn additional pause chances (prevents ₱1 pause exploits)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, default='', help_text='Authorized Telegram Admin Chat ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Telegram Bot Token from @BotFather', max_length=150),
        ),
    ]
