# Generated by Django 4.2.16 on 2026-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500)),
                ('csv_file_path', models.CharField(blank=True, max_length=500)),
                ('delivered_to', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Delivery Log',
                'verbose_name_plural': 'Report Delivery Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
